version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: puppeteer
    versions:
    - 3.3.0
    - 7.1.0
    - 8.0.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: chalk
    versions:
    - 4.1.0
